import { Activity, BarChart3, Bot, RadioTower, ShieldCheck, ShieldX, TrendingUp } from "lucide-react";
import { useEffect, useState } from "react";
import { CardSkeleton, EmptyState } from "../components/ui/Feedback";
import { StatusBadge } from "../components/ui/StatusBadge";
import { apiClient } from "../lib/api-client";
import type { AdvancedAnalytics, AnalyticsRange } from "../types/api";

const ranges: Array<[AnalyticsRange, string]> = [["1h", "1 hour"], ["24h", "24 hours"], ["7d", "7 days"], ["all", "All time"]];
export function AnalyticsPage() {
  const [range, setRange] = useState<AnalyticsRange>("24h"); const [data, setData] = useState<AdvancedAnalytics | null>(null); const [error, setError] = useState(false);
  useEffect(() => { const c = new AbortController(); setData(null); apiClient.advancedAnalytics(range, c.signal).then((value) => { setData(value); setError(false); }).catch(() => { if (!c.signal.aborted) setError(true); }); return () => c.abort(); }, [range]);
  const metrics = data?.metrics;
  return <div className="page-stack stage7-page analytics-page"><header className="product-page-header stage7-header"><div><p className="eyebrow"><BarChart3 /> Persistent operational intelligence</p><h2>Advanced Analytics</h2><p>Registry, audit, interaction, and blockchain lifecycle metrics calculated from real records—not seeded dashboard totals.</p></div><div className="range-switch" role="group" aria-label="Analytics time range">{ranges.map(([value, label]) => <button type="button" className={range === value ? "is-active" : ""} key={value} onClick={() => setRange(value)}>{label}</button>)}</div></header>
    {!data && !error ? <section className="metric-grid"><CardSkeleton /><CardSkeleton /><CardSkeleton /><CardSkeleton /></section> : error ? <EmptyState kind="network" title="Analytics unavailable" description="Persistent activity or the local registry could not be reached." /> : data && <><section className="metric-grid analytics-metrics"><Metric icon={Bot} label="Identities" value={metrics!.identities} detail={`${metrics!.activeIdentities} active · ${metrics!.revokedIdentities} revoked`} /><Metric icon={Activity} label="Verification attempts" value={metrics!.verificationAttempts} detail={`${metrics!.verifiedRequests} verified · ${metrics!.blockedRequests} blocked`} /><Metric icon={TrendingUp} label="Success rate" value={`${metrics!.successRate}%`} detail="Verified audit attempts ÷ total audit attempts" /><Metric icon={RadioTower} label="Interactions" value={metrics!.interactions} detail="Receiver executions after authentication" /><Metric icon={ShieldCheck} label="Unique active agents" value={metrics!.uniqueActiveAgents} detail="Active identities in filtered interactions" /></section>
      {metrics!.verificationAttempts === 0 && metrics!.interactions === 0 ? <EmptyState title="No activity in this time range" description="Choose a broader range or run a controlled communication scenario." kind="activity" /> : <section className="analytics-grid"><Chart title="Verification outcomes" eyebrow="Time series" rows={data.verificationSeries.map((item) => ({ label: new Date(item.timestamp).toLocaleString(), primary: item.VERIFIED ?? 0, secondary: item.BLOCKED ?? 0 }))} primaryLabel="Verified" secondaryLabel="Blocked" /><Ranked title="Blocked by reason" eyebrow="Security controls" rows={data.blockedReasons} icon={ShieldX} /><Ranked title="Most active agents" eyebrow="Authenticated traffic" rows={data.activeAgents} icon={Bot} /><Ranked title="Communication pairs" eyebrow="Verified routes" rows={data.communicationPairs} icon={RadioTower} /><Ranked title="Lifecycle activity" eyebrow="On-chain events" rows={data.lifecycleActivity} icon={ShieldCheck} /><Chart title="Verified interactions" eyebrow="Time series" rows={data.interactionSeries.map((item) => ({ label: new Date(item.timestamp).toLocaleString(), primary: item.INTERACTION ?? 0, secondary: 0 }))} primaryLabel="Interactions" /></section>}
      <footer className="analytics-source"><StatusBadge tone="active" label="REAL RECORDS" /><span>Calculated {new Date(data.generatedAt).toLocaleString()} · {data.source.replaceAll("_", " ").toLowerCase()}</span></footer></>}
  </div>;
}
function Metric({ icon: Icon, label, value, detail }: { icon: typeof Bot; label: string; value: string | number; detail: string }) { return <article className="metric-card"><header><span><Icon /></span><StatusBadge tone="active" label="LIVE" /></header><p>{label}</p><strong>{value}</strong><small>{detail}</small></article>; }
function Ranked({ title, eyebrow, rows, icon: Icon }: { title: string; eyebrow: string; rows: Array<{ label: string; value: number }>; icon: typeof Bot }) { const max = Math.max(1, ...rows.map((item) => item.value)); return <section className="panel ranked-chart"><header><div><p className="eyebrow">{eyebrow}</p><h3>{title}</h3></div><Icon /></header>{rows.length ? <div>{rows.slice(0, 8).map((item) => <article key={item.label}><span><strong>{item.label}</strong><i><b style={{ width: `${item.value / max * 100}%` }} /></i></span><em>{item.value}</em></article>)}</div> : <EmptyState title="No matching records" description="This view will populate from real activity." kind="activity" />}</section>; }
function Chart({ title, eyebrow, rows, primaryLabel, secondaryLabel }: { title: string; eyebrow: string; rows: Array<{ label: string; primary: number; secondary: number }>; primaryLabel: string; secondaryLabel?: string }) { const max = Math.max(1, ...rows.flatMap((item) => [item.primary, item.secondary])); return <section className="panel time-chart"><header><div><p className="eyebrow">{eyebrow}</p><h3>{title}</h3></div><div className="chart-legend"><span><i />{primaryLabel}</span>{secondaryLabel && <span><i />{secondaryLabel}</span>}</div></header>{rows.length ? <div className="chart-bars">{rows.slice(-12).map((item) => <article key={item.label} title={item.label}><span><i style={{ height: `${Math.max(4, item.primary / max * 100)}%` }} /><i style={{ height: `${item.secondary / max * 100}%` }} /></span><small>{new Date(item.label).toLocaleTimeString([], { hour: "2-digit" })}</small></article>)}</div> : <EmptyState title="No timeline data" description="Real events will appear after authentication activity." kind="activity" />}</section>; }
