import { Blocks, Box, Fuel, RadioTower, SearchCode, ScrollText } from "lucide-react";
import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { CardSkeleton, EmptyState } from "../components/ui/Feedback";
import { SearchInput } from "../components/ui/FormControls";
import { StatusBadge } from "../components/ui/StatusBadge";
import { TechnicalValue } from "../components/ui/TechnicalValue";
import { apiClient } from "../lib/api-client";
import type { ExplorerResponse } from "../types/api";

export function ExplorerPage() {
  const [data, setData] = useState<ExplorerResponse | null>(null); const [query, setQuery] = useState(""); const [selectedBlock, setSelectedBlock] = useState<number | null>(null); const [error, setError] = useState(false);
  useEffect(() => { const c = new AbortController(); const id = window.setTimeout(() => apiClient.explorer(query, c.signal).then((value) => { setData(value); setError(false); }).catch(() => { if (!c.signal.aborted) setError(true); }), query ? 250 : 0); return () => { window.clearTimeout(id); c.abort(); }; }, [query]);
  const matchCount = data ? Object.values(data.matches).reduce((sum, items) => sum + items.length, 0) : 0;
  return <div className="page-stack stage7-page explorer-page"><header className="product-page-header stage7-header"><div><p className="eyebrow"><SearchCode /> Local chain evidence</p><h2>AgentID Explorer</h2><p>Inspect the connected Hardhat chain, AgentRegistry lifecycle transactions, decoded events, receipts, and gas usage.</p></div><StatusBadge tone={data?.network.connected ? "active" : "offline"} label={data?.network.connected ? `CHAIN ${data.network.chainId}` : "OFFLINE"} /></header>
    <section className="explorer-search panel"><SearchInput aria-label="Search blockchain explorer" placeholder="Search AgentID, wallet, transaction hash, or block" value={query} onChange={(event) => setQuery(event.target.value)} />{query && <span>{matchCount} real match{matchCount === 1 ? "" : "es"}</span>}</section>
    {!data && !error ? <CardSkeleton /> : error ? <EmptyState kind="network" title="Explorer unavailable" description="The local Ethereum RPC or AgentID backend is not reachable." /> : data && <><section className="metric-grid explorer-metrics"><Metric icon={Blocks} label="Latest block" value={String(data.network.latestBlock ?? "—")} /><Metric icon={RadioTower} label="Network" value={`${data.network.network} · ${data.network.chainId}`} /><Metric icon={ScrollText} label="Lifecycle events" value={String(data.events.length)} /><Metric icon={Fuel} label="Tracked transactions" value={String(data.transactions.length)} /></section>
      <section className="explorer-contract panel"><div><p className="eyebrow">Contract source of truth</p><h3>AgentRegistry</h3></div><TechnicalValue value={data.contractAddress} label="AgentRegistry address" /></section>
      {query && <section className="panel explorer-results"><header><div><p className="eyebrow">Search results</p><h3>Matching on-chain records</h3></div></header>{matchCount ? <div>{data.matches.agents.map((agent) => <article key={agent.agentId}><BotLine title={agent.agentId} detail={`${agent.name} · ${agent.owner}`} /></article>)}{data.matches.transactions.map((tx) => <article key={tx.hash}><BotLine title={`${tx.operation} · ${tx.agentId}`} detail={tx.hash} /></article>)}{data.matches.blocks.map((block) => <article key={block.number}><BotLine title={`Block ${block.number}`} detail={block.hash} /></article>)}</div> : <EmptyState kind="agents" title="No blockchain match" description="Try an AgentID, wallet, transaction hash, or exact block number." />}</section>}
      <section className="explorer-grid"><div className="panel explorer-blocks"><header><div><p className="eyebrow">Canonical chain</p><h3>Recent blocks</h3></div><Blocks /></header>{data.blocks.map((block) => <article className={selectedBlock === block.number ? "is-selected" : ""} key={block.number}><button type="button" className="block-open" onClick={() => setSelectedBlock(selectedBlock === block.number ? null : block.number)}><span><Box /></span><div><strong>Block {block.number}</strong><small>{new Date(block.timestamp * 1000).toLocaleString()} · {block.transactionCount} transaction{block.transactionCount === 1 ? "" : "s"}</small></div></button><TechnicalValue value={block.hash} label="block hash" /></article>)}{selectedBlock !== null && data.blocks.filter((block) => block.number === selectedBlock).map((block) => <dl className="block-detail" key={`detail-${block.number}`}><div><dt>Parent hash</dt><dd><TechnicalValue value={block.parentHash} label="parent block hash" /></dd></div><div><dt>Timestamp</dt><dd>{new Date(block.timestamp * 1000).toLocaleString()}</dd></div><div><dt>Transactions</dt><dd>{block.transactionCount}</dd></div></dl>)}</div>
        <div className="panel explorer-transactions"><header><div><p className="eyebrow">AgentRegistry receipts</p><h3>Relevant transactions</h3></div><ScrollText /></header>{data.transactions.length ? data.transactions.map((tx) => <details key={tx.hash}><summary><span><StatusBadge tone={tx.status === "CONFIRMED" ? "verified" : "blocked"} label={tx.operation} /><strong>{tx.agentId}</strong></span><code>Block {tx.blockNumber}</code></summary><dl><div><dt>Transaction</dt><dd><TechnicalValue value={tx.hash} label="transaction hash" /></dd></div><div><dt>From</dt><dd><TechnicalValue value={tx.from} label="sender wallet" /></dd></div><div><dt>To</dt><dd><TechnicalValue value={tx.to} label="contract address" /></dd></div><div><dt>Gas used</dt><dd>{Number(tx.gasUsed).toLocaleString()}</dd></div></dl></details>) : <EmptyState title="No lifecycle transactions" description="Register or update an identity to create explorer activity." kind="activity" />}</div></section>
      <section className="panel explorer-events"><header><div><p className="eyebrow">Decoded AgentRegistry logs</p><h3>Contract event feed</h3></div><ActivityIcon /></header>{data.events.length ? <div>{data.events.map((event) => <article key={`${event.transactionHash}-${event.type}`}><StatusBadge tone={event.type === "Revoked" ? "revoked" : "verified"} label={`Agent${event.type}`} /><span><Link to={`/app/registry/${event.agentId}`}>{event.agentId}</Link><small>Block {event.blockNumber} · {new Date(Number(event.timestamp) * 1000).toLocaleString()}</small></span><TechnicalValue value={event.transactionHash} label="event transaction hash" /></article>)}</div> : <EmptyState title="No contract events" description="AgentRegistry lifecycle events will appear here." kind="activity" />}</section>
      <section className="panel gas-insights"><header><div><p className="eyebrow">Receipt-derived efficiency</p><h3>Gas insights by operation</h3></div><Fuel /></header><div>{data.gasByOperation.map((item) => <article key={item.operation}><strong>{item.operation}</strong><span>{item.count} transaction{item.count === 1 ? "" : "s"}</span><b>{Number(item.averageGasUsed).toLocaleString()} avg gas</b></article>)}</div></section></>}
  </div>;
}
function Metric({ icon: Icon, label, value }: { icon: typeof Blocks; label: string; value: string }) { return <article className="metric-card"><header><span><Icon /></span></header><p>{label}</p><strong>{value}</strong><small>Live local RPC</small></article>; }
function BotLine({ title, detail }: { title: string; detail: string }) { return <><span><SearchCode /></span><div><strong>{title}</strong><small>{detail}</small></div></>; }
function ActivityIcon() { return <ScrollText />; }
