import { Beaker, CheckCircle2, FlaskConical, LockKeyhole, Play, ShieldAlert, ShieldCheck, ShieldX } from "lucide-react";
import { useEffect, useState } from "react";
import { Button } from "../components/ui/Button";
import { CardSkeleton, EmptyState } from "../components/ui/Feedback";
import { StatusBadge } from "../components/ui/StatusBadge";
import { apiClient, ApiError } from "../lib/api-client";
import type { SecurityScenarioId, SecurityScenarioInfo, SecurityScenarioResult } from "../types/api";

export function SecurityLabPage() {
  const [scenarios, setScenarios] = useState<SecurityScenarioInfo[]>([]); const [selected, setSelected] = useState<SecurityScenarioId>("VALID"); const [result, setResult] = useState<SecurityScenarioResult | null>(null); const [history, setHistory] = useState<SecurityScenarioResult[]>([]); const [running, setRunning] = useState(false); const [error, setError] = useState("");
  useEffect(() => { const c = new AbortController(); apiClient.securityScenarios(c.signal).then((value) => setScenarios(value.scenarios)).catch(() => setError("Security Lab metadata is unavailable.")); return () => c.abort(); }, []);
  const run = async () => { setRunning(true); setError(""); setResult(null); try { const next = await apiClient.runSecurityScenario(selected); setResult(next); setHistory((items) => [...items, next]); } catch (cause) { setError(cause instanceof ApiError ? cause.message : "The controlled scenario could not be completed."); } finally { setRunning(false); } };
  return <div className="page-stack stage7-page security-lab-page"><header className="product-page-header stage7-header"><div><p className="eyebrow"><FlaskConical /> Controlled authentication tests</p><h2>Security Lab</h2><p>Execute one whitelisted scenario against the real local authentication pipeline. Receiver code remains gated behind successful verification.</p></div><StatusBadge tone="pending" label="LOCAL DEV · 31337" /></header>
    <section className="security-guard panel"><LockKeyhole /><div><strong>Guarded execution environment</strong><p>Predefined scenarios only. No arbitrary payload signing, wallet selection, contract address, or network target is exposed.</p></div></section>
    <section className="security-summary" aria-label="Executed scenario summary"><article><small>Tests run</small><strong>{history.length}</strong></article><article><small>Protected as expected</small><strong>{history.filter((item) => item.protectedAsExpected).length}</strong></article><article><small>Blocked attacks</small><strong>{history.filter((item) => item.scenario !== "VALID" && !item.result.receiverExecuted).length}</strong></article><p>Counts include only scenarios executed in this browser session. They do not claim the system is unhackable.</p></section>
    {!scenarios.length && !error ? <CardSkeleton /> : <section className="security-lab-grid"><div className="panel scenario-catalog"><header><div><p className="eyebrow">Scenario catalog</p><h3>Choose one test</h3></div><Beaker /></header>{scenarios.map((scenario) => <button type="button" className={selected === scenario.id ? "is-selected" : ""} key={scenario.id} onClick={() => { setSelected(scenario.id); setResult(null); }}><span>{scenario.id === "VALID" ? <ShieldCheck /> : <ShieldAlert />}</span><span><strong>{scenario.id.replaceAll("_", " ")}</strong><small>{scenario.description}</small></span><code>{scenario.expectedCode}</code></button>)}<Button icon={Play} onClick={run} loading={running} disabled={!scenarios.length}>Run controlled scenario</Button></div>
      <div className="panel scenario-result">{error ? <EmptyState kind="network" title="Scenario unavailable" description={error} /> : !result ? <EmptyState title="Ready for a controlled test" description="Select a scenario and run it. A real EIP-712 request will pass through the existing authentication service." kind="activity" /> : <><header><span className={result.protectedAsExpected ? "result-pass" : "result-fail"}>{result.protectedAsExpected ? <CheckCircle2 /> : <ShieldX />}</span><div><p className="eyebrow">Observed result</p><h3>{result.protectedAsExpected ? "Protection behaved as expected" : "Unexpected security outcome"}</h3></div><StatusBadge tone={result.result.verification.verified ? "verified" : "blocked"} label={result.result.verification.code} /></header><div className="scenario-route"><strong>{result.request.senderAgentId}</strong><span>signed request</span><strong>{result.request.receiverAgentId}</strong></div><ol>{result.checkpoints.map((checkpoint) => <li key={checkpoint.label} className={`is-${checkpoint.status.toLowerCase()}`}><span>{checkpoint.status === "PASS" ? <CheckCircle2 /> : checkpoint.status === "BLOCKED" ? <ShieldX /> : <Beaker />}</span><div><strong>{checkpoint.label}</strong><small>{checkpoint.detail}</small></div><code>{checkpoint.status}</code></li>)}</ol><dl><div><dt>Expected</dt><dd>{result.expectedCode}</dd></div><div><dt>Observed</dt><dd>{result.result.verification.code}</dd></div><div><dt>Receiver executed</dt><dd>{result.result.receiverExecuted ? "YES" : "NO"}</dd></div><div><dt>Duration</dt><dd>{result.durationMs} ms</dd></div></dl><details><summary>Signed request evidence</summary><pre>{JSON.stringify({ request: result.request, verification: result.result.verification, guardrails: result.guardrails }, null, 2)}</pre></details></>}</div>
    </section>}
  </div>;
}
