import { Activity, Bot, GitBranch, Minus, Plus, Scan, ShieldCheck, ShieldX } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { CardSkeleton, EmptyState } from "../components/ui/Feedback";
import { SearchInput, Select } from "../components/ui/FormControls";
import { StatusBadge } from "../components/ui/StatusBadge";
import { TechnicalValue } from "../components/ui/TechnicalValue";
import { apiClient } from "../lib/api-client";
import type { TrustGraphResponse } from "../types/api";

export function TrustGraphPage() {
  const [data, setData] = useState<TrustGraphResponse | null>(null); const [query, setQuery] = useState(""); const [status, setStatus] = useState("ALL"); const [category, setCategory] = useState("ALL"); const [capability, setCapability] = useState("ALL"); const [edgeMode, setEdgeMode] = useState("ALL"); const [zoom, setZoom] = useState(1); const [selected, setSelected] = useState<string | null>(null); const [error, setError] = useState(false);
  useEffect(() => { const c = new AbortController(); apiClient.trustGraph(c.signal).then((value) => { setData(value); setError(false); }).catch(() => { if (!c.signal.aborted) setError(true); }); return () => c.abort(); }, []);
  const nodes = useMemo(() => (data?.nodes ?? []).filter((node) => (status === "ALL" || node.status === status) && (category === "ALL" || node.category === category) && (capability === "ALL" || node.capabilities.includes(capability)) && `${node.agentId} ${node.displayName} ${node.organization} ${node.owner}`.toLowerCase().includes(query.toLowerCase())), [data, query, status, category, capability]);
  const nodeIds = new Set(nodes.map((node) => node.agentId)); const edges = (data?.edges ?? []).filter((edge) => nodeIds.has(edge.source) && nodeIds.has(edge.target) && (edgeMode === "ALL" || (edgeMode === "VERIFIED" ? edge.verified > 0 : edge.blocked > 0))); const detail = data?.nodes.find((node) => node.agentId === selected); const categories = [...new Set((data?.nodes ?? []).map((node) => node.category).filter(Boolean))] as string[]; const capabilities = [...new Set((data?.nodes ?? []).flatMap((node) => node.capabilities))];
  return <div className="page-stack stage7-page trust-graph-page"><header className="product-page-header stage7-header"><div><p className="eyebrow"><GitBranch /> Registry relationships</p><h2>Trust Graph</h2><p>On-chain identities connected only by real verified deliveries and blocked authentication attempts. No inferred reputation or trust score.</p></div><StatusBadge tone="active" label="LIVE DATA" /></header>
    <section className="stage7-toolbar panel"><SearchInput aria-label="Search trust graph" placeholder="Search AgentID, wallet, or organization" value={query} onChange={(event) => setQuery(event.target.value)} /><Select aria-label="Filter identity status" value={status} onChange={(event) => setStatus(event.target.value)}><option value="ALL">All statuses</option><option value="Active">Active only</option><option value="Revoked">Revoked only</option></Select><Select aria-label="Filter category" value={category} onChange={(event) => setCategory(event.target.value)}><option value="ALL">All categories</option>{categories.map((item) => <option key={item}>{item}</option>)}</Select><Select aria-label="Filter capability" value={capability} onChange={(event) => setCapability(event.target.value)}><option value="ALL">All capabilities</option>{capabilities.map((item) => <option key={item}>{item}</option>)}</Select><Select aria-label="Filter edge type" value={edgeMode} onChange={(event) => setEdgeMode(event.target.value)}><option value="ALL">All edges</option><option value="VERIFIED">Verified edges</option><option value="BLOCKED">Blocked edges</option></Select><span><ShieldCheck /> {edges.reduce((sum, edge) => sum + edge.verified, 0)} verified</span><span><ShieldX /> {edges.reduce((sum, edge) => sum + edge.blocked, 0)} blocked</span></section>
    {!data && !error ? <CardSkeleton /> : error ? <EmptyState kind="network" title="Trust graph unavailable" description="Start the local blockchain and backend, then refresh." /> : nodes.length === 0 ? <EmptyState kind="agents" title="No matching identities" description="Change the graph filters to reveal registered identities." /> : <section className="trust-graph-layout"><div className="panel trust-canvas" aria-label="Agent trust graph"><div className="graph-controls" aria-label="Graph zoom controls"><button type="button" aria-label="Zoom out" onClick={() => setZoom((value) => Math.max(.75, value - .15))}><Minus /></button><button type="button" aria-label="Fit graph to view" onClick={() => setZoom(1)}><Scan /></button><button type="button" aria-label="Zoom in" onClick={() => setZoom((value) => Math.min(1.45, value + .15))}><Plus /></button></div><div className="trust-scene" style={{ transform: `scale(${zoom})` }}><div className="trust-lines" aria-hidden="true">{edges.flatMap((edge, index) => [edge.verified > 0 && edgeMode !== "BLOCKED" ? <span key={`${edge.source}-${edge.target}-verified`} className="is-verified" style={{ top: `${25 + (index % 4) * 17}%`, left: `${13 + (index % 3) * 20}%`, width: `${35 + (index % 2) * 12}%`, rotate: `${-12 + index * 9}deg` }} /> : null, edge.blocked > 0 && edgeMode !== "VERIFIED" ? <span key={`${edge.source}-${edge.target}-blocked`} className="is-blocked" style={{ top: `${28 + (index % 4) * 17}%`, left: `${14 + (index % 3) * 20}%`, width: `${34 + (index % 2) * 12}%`, rotate: `${-10 + index * 9}deg` }} /> : null])}</div><div className="trust-nodes">{nodes.map((node, index) => { const incoming = edges.filter((edge) => edge.target === node.agentId); const outgoing = edges.filter((edge) => edge.source === node.agentId); return <button type="button" title={`${node.agentId}\n${node.owner}\n${node.organization}\n${node.capabilities.join(", ") || "No capabilities"}\n${node.status}\nRegistered block ${node.registrationBlock ?? "unknown"}\n${incoming.length + outgoing.length} observed routes`} key={node.agentId} className={`trust-node node-${index % 6} ${selected === node.agentId ? "is-selected" : ""}`} onClick={() => setSelected(node.agentId)}><span><Bot /></span><strong>{node.displayName}</strong><small>{node.agentId}</small><StatusBadge tone={node.status === "Active" ? "active" : "revoked"} /><em>{outgoing.reduce((sum, edge) => sum + edge.verified, 0)} sent · {incoming.reduce((sum, edge) => sum + edge.verified, 0)} received</em></button>; })}</div></div><div className="trust-legend"><span><i className="verified-line" /> verified interaction</span><span><i className="blocked-line" /> blocked attempt</span><span><Activity /> persisted activity only</span></div></div>
      <aside className="panel trust-detail">{detail ? <><p className="eyebrow">Selected identity</p><h3>{detail.displayName}</h3><StatusBadge tone={detail.status === "Active" ? "active" : "revoked"} /><dl><div><dt>AgentID</dt><dd>{detail.agentId}</dd></div><div><dt>Organization</dt><dd>{detail.organization}</dd></div><div><dt>Category</dt><dd>{detail.category ?? "Not specified"}</dd></div><div><dt>Registration block</dt><dd>{detail.registrationBlock ?? "Unavailable"}</dd></div></dl><TechnicalValue value={detail.owner} label="owner wallet" /><div className="capability-list">{detail.capabilities.map((item) => <span key={item}>{item}</span>)}</div><h4>Observed edges</h4>{edges.filter((edge) => edge.source === detail.agentId || edge.target === detail.agentId).map((edge) => <article key={`${edge.source}-${edge.target}`}><strong>{edge.source} → {edge.target}</strong><small>{edge.verified} verified · {edge.blocked} blocked</small></article>)}<Link className="button button-secondary" to={`/app/registry/${detail.agentId}`}>Open passport</Link></> : <EmptyState title="Select an identity" description="Choose a node to inspect its blockchain identity and observed communication edges." kind="agents" />}</aside></section>}
  </div>;
}
